import type { Params } from "./type";

export const englishTextMap = {
  activityList: {
    title: "Activity List",
    createNew: "Create New Activity",
    newActivity: "New Activity",
    activityName: "Activity Name",
    loadingActivities: "Loading activities...",
    activitiesError: "Error loading activities",
    activitiesEmpty: "No activities found.",
    viewClasses: "Show Classes",
    filters: {
      name: {
        title: "Name",
        placeholder: "Activity Name",
      },
      area: {
        title: "Area",
        placeholder: "Select Area",
        sports: "Sports",
        gym: "Gym",
        water: "Water Sports",
      },
      frequency: {
        title: "Frequency",
        placeholder: "Select Frequency",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
      },
    },
    card: {
      area: "Area:",
      frequency: "Frequency:",
      teacher: "Teacher:",
    },
  },
  anamnesis: {
    title: "Anamnesis Form",
    createNew: "Create new form",
    previousForms: "Previous Forms",
    skip: "Skip",
    save: "Save",
    selectOrCreate: "Select a form or create a new one.",
  },
  classes: {
    title: "My Classes",
    loadingClasses: "Loading classes...",
    classesError: "Error loading classes",
    createClass: "Create class",
    weekDay: "Weekday",
    schedule: "Schedule",
    level: "Level",
    activity: "Activity",
    card: {
      level: "Level:",
      teacher: "Teacher:"
    },
  },
  classDetails: {
    loading: "Loading class details...",
    errorLoading: "Error loading class data.",
    classNotFound: "Class not found.",
    editClass: "Edit Class",
    professor: "Teacher",
    level: "Level",
    frequency: "Frequency",
    noStudents: "Class does not have students.",
  },
  dateInput: {
    selectDate: "Select date",
  },
  errorBoundary: {
    title: "Oops",
    message: "Something went wrong. You can reload the page or go back to the home screen.",
    goHome: "Go Home",
    reload: "Reload",
  },
  filters: {
    loading: "Loading filters...",
    all: "All",
    formType: {
      title: "Form Types",
      psychology: "Psychology",
      social: "Social Work",
    },
    userStatus: {
      title: "User Status",
      active: "Active",
      inactive: "Inactive",
    },
    studentStatus: {
      title: "Student Status",
      active: "Active",
      inactive: "Inactive",
    },
    frequencyStatus: {
      title: "Attendance Status",
      present: "Present",
      absent: "Absent",
    },
    classState: {
      title: "Class Status",
      active: "Active",
      inactive: "Inactive",
    },
    race: {
      title: "Race",
      white: "White",
      black: "Black",
      brown: "Brown",
      yellow: "Asian",
      indigenous: "Indigenous",
      notDeclared: "Not Declared",
    },
    gender: {
      title: "Gender",
      male: "Male",
      female: "Female",
      transMan: "Trans Man",
      transWoman: "Trans Woman",
      nonBinary: "Non-Binary",
      other: "Other",
    },
    socialPrograms: {
      title: "Social Programs",
      bolsaFamilia: "Bolsa Família",
      bpcLoas: "BPC/LOAS",
      tarifaSocialDeEnergia: "Social Energy Tariff",
      auxilioGas: "Gas Aid",
      programaEstadual: "State Program",
      programaMunicipalViaCras: "Municipal Program via CRAS",
    },
    employmentStatus: {
      title: "Employment Status",
      student: "Student",
      employed: "Employed",
      unemployed: "Unemployed",
      intern: "Intern",
      apprentice: "Apprentice",
      selfEmployed: "Self-Employed",
      other: "Other",
    },
    schoolYear: {
      title: "School Year",
      infantileEducation: "Infantile Education",
      elementary1: "Elementary 1",
      elementary2: "Elementary 2",
      elementary3: "Elementary 3",
      elementary4: "Elementary 4",
      elementary5: "Elementary 5",
      elementary6: "Elementary 6",
      elementary7: "Elementary 7",
      elementary8: "Elementary 8",
      elementary9: "Elementary 9",
      highSchool1: "High School 1",
      highSchool2: "High School 2",
      highSchool3: "High School 3",
      eja: "EJA",
    },
    educationLevel: {
      title: "Education Level",
      none: "None",
      literate: "Literate",
      incompleteElementary: "Elementary Incomplete",
      completeElementary: "Elementary Complete",
      incompleteHighSchool: "High School Incomplete",
      completeHighSchool: "High School Complete",
      incompleteHigher: "Higher Education Incomplete",
      completeHigher: "Higher Education Complete",
      posGraduation: "Post-Graduation",
    },
    noteTypes: {
      title: "Note Types",
      medical: "Medical",
      none: "None",
      empty: "(empty)",
    },
    weekDays: {
      title: "Week Day",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
    },
    role: {
      title: "Role",
      admin: "Admin",
      manager: "Manager",
      teacher: "Teacher",
      psychologist: "Psychologist",
      psychology_intern: "Psychology Intern",
      social_worker: "Social Worker",
      social_work_intern: "Social Work Intern",
    },
    identityTypes: {
      title: "Document Type",
      rg: "RG",
      cpf: "CPF",
      birthCertificate: "Birth Certificate",
      driverLicense: "Driver's License",
      passport: "Passport",
      voterRegistration: "Voter Registration",
      ctps: "CTPS",
      other: "Other",
    },
    documentTypes: {
      title: "Document Type",
      residenceProof: "Proof of Residence",
      incomeProof: "Proof of Income",
      other: "Other",
    },
    levels: {
      title: "Level",
      beginner: "Beginner",
      intermediate: "Intermediate",
      advanced: "Advanced",
    },
    civilStates: {
      title: "Civil Status",
      single: "Single",
      married: "Married",
      divorced: "Divorced",
      widowed: "Widowed",
      stableUnion: "Stable Union",
    },
  },
  frequency: {
    title: "Take Attendance",
    loadingActivities: "Loading activities...",
    activitiesError: "Error loading activities",
  },
  frequencyCall: {
    title: ({ activity, classTitle }: Params<"activity" | "classTitle">) => (
      `Attendance - ${activity} - ${classTitle}`
    ),
    loadingStudents: "Loading students...",
    studentsError: "Error loading students",
    errorNoStudents: "Error saving attendance, students not found",
    errorNoDate: "Error saving attendance, please enter a date",
    successSave: "Attendance recorded successfully",
  },
  frequencyCard: {
    absentDetails: "Add Observation",
    frequency: ({ percent }: Params<"percent">) => (
      `Attendance: ${percent}%`
    ),
    active: "Active",
    inactive: "Inactive",
  },
  frequencyClasses: {
    title: ({ activity }: Params<"activity">) => `Take Attendance - ${activity}`,
    loadingClasses: "Loading classes...",
    classesError: "Error loading classes",
    noClasses: "No classes found for this activity.",
    goBack: "Back to Activities",
  },
  genericActions: {
    cancel: "Cancel",
    create: "Create",
    delete: "Delete",
    edit: "Edit",
    loading: "Loading...",
    save: "Save",
    saveEdit: "Save Changes",
    viewDetails: "View Details",
    toggleStatusOn: "Activate",
    toggleStatusOff: "Deactivate",
  },
  frequencyGeneralCall: {
    title: "General Attendance",
    save: "Save",
    loadingStudents: "Loading students...",
    studentsError: "Error loading students",
    errorNoStudents: "Error saving attendance, students not found",
    errorNoDate: "Error saving attendance, please enter a date",
    successSave: "Attendance saved successfully",
    errorInvalidDate: "Invalid date format",
    errorServer: "An unexpected internal server error occurred",
  },
  header: {
    goToHome: "Go to home page",
    logoAlt: "WimBelemDon logo",
  },
  home: {
    welcomeBack: "Welcome back",
    cards: {
      takeAttendance: "Take Attendance",
      manageStudents: "Manage Students",
      manageActivities: "Manage Activities",
      manageClasses: "Manage Classes",
      manageUsers: "Manage Users"
    }
  },
  login: {
    title: "Login",
    loginWithGoogle: "Login with Google",
    loggingIn: "Logging in...",
    logoAlt: "Logo",
    errors: {
      invalidToken: "Invalid sign-in token. Please try again.",
      notRegistered: "Your account is not registered in the system.",
      inactive: "Your account is not active. Please contact an administrator.",
      popupClosed: "Sign-in was cancelled before completion.",
      popupBlocked: "The sign-in popup was blocked by your browser.",
      popupCancelled: "Another sign-in attempt was in progress.",
      network: "Network error during sign-in. Check your connection and try again.",
      generic: "We couldn't sign you in. Please try again.",
    }
  },
  newResponsibleModal: {
    title: "Register Responsible",
    buttonText: "Add Responsible",
    personalInformation: "Personal Information",
    employmentInformation: "Employment Information",
    addressInformation: "Address",
    inputs: {
      name: "Full Name",
      namePlaceholder: "Enter Responsible's full name",
      socialName: "Social Name",
      socialNamePlaceholder: "Enter Responsible's social name",
      cpf: "CPF",
      cpfPlaceholder: "Enter Responsible's CPF",
      registrationNumber: "Registration Number",
      registrationNumberPlaceholder: "Enter registration number",
      birthDate: "Date of Birth",
      birthDatePlaceholder: "Enter Responsible's date of birth",
      civilState: "Civil Status",
      civilStatePlaceholder: "Select Responsible's civil status",
      nis: "NIS",
      nisPlaceholder: "Enter Responsible's NIS",
      phone: "Phone",
      phonePlaceholder: "Enter Responsible's phone",
      email: "Email",
      emailPlaceholder: "Enter Responsible's email",
      relationship: "Relationship",
      relationshipPlaceholder: "Enter relationship to student",
      race: "Race",
      racePlaceholder: "Select race",
      gender: "Gender",
      genderPlaceholder: "Select gender",
      educationLevel: "Education Level",
      educationLevelPlaceholder: "Select education level",
      socialPrograms: "Social Programs",
      socialProgramsPlaceholder: "Select social programs",
      employmentStatus: "Employment Status",
      employmentStatusPlaceholder: "Select employment status",
      street: "Street",
      streetPlaceholder: "Enter street address",
      neighborhood: "Neighborhood",
      neighborhoodPlaceholder: "Enter neighborhood",
      city: "City",
      cityPlaceholder: "Enter city",
      state: "State",
      statePlaceholder: "Enter state",
      cep: "ZIP Code",
      cepPlaceholder: "Enter ZIP code",
      number: "Number",
      numberPlaceholder: "Enter number",
      complement: "Complement",
      complementPlaceholder: "Apartment, block, house, etc.",
      address: "Address",
      addressPlaceholder: "Enter Responsible's address",
    },
    requiredFields: {
      fullName: "Full name is required.",
      registrationNumber: "CPF is required.",
      birthDate: "Date of birth is required.",
      phone: "Phone is required.",
      relationship: "Relationship is required.",
      cep: "ZIP code is required.",
      number: "Number is required.",
    },
    successMessage: "Responsible added successfully!",
    pleaseFillAllFields: "Please fill in all required fields.",
  },
  notFound: {
    title: "Page not found",
    message: "The page you're looking for doesn't exist.",
    goHome: "Go Home",
    reload: "Reload",
  },
  classesModal: {
    title: "Create Class",
    recurring: "Recurring Activity",
    inputs: {
      className: "Class Name",
      classLevel: "Class Level",
      startDate: "Start Date",
      endDate: "End Date",
      startTime: "Start Time",
      endTime: "End Time",
      level: "Level",
      searchTeacher: "Search Teacher",
      assignTeacher: "Assign Teacher",
      searchStudent: "Search Student",
      addStudent: "Add Student",
    },
    buttons: {
      next: "Next",
      back: "Back",
      create: "Create",
    },
    steps: {
      data: "Data",
      teacher: "Teachers",
      student: "Educandos",
    },
    createSuccessMessage: "Class created successfully!",
    createErrorFillAllFields: "Please fill in all fields.",
    createErrorGeneric: "Error creating class. Please try again.",
  },
  personCard: {
    userImageAlt: "User image",
    fullName: "Full Name:",
    socialName: "Social Name:",
    registrationNumber: "CPF:",
    dateOfBirth: "Date of Birth:",
    nis: "NIS:",
    phoneNumber: "Phone:",
    email: "Email:",
    address: "Address:",
    relationship: "Relationship:",
    race: "Race:",
    gender: "Gender:",
    educationLevel: "Education Level:",
    socialPrograms: "Social Programs:",
    employmentStatus: "Employment Status:",
  },
  sidebar: {
    openSidebar: "Open sidebar menu",
    listIcon: ({ to }: Params<"to">) => (
      `Navigate to ${to} page`
    ),
    home: "Home",
    frequency: "Frequency",
    students: "Students",
    activities: "Activities",
    classes: "Classes",
    users: "Users",
    techDemo: "Tech Demo"
  },
  studentRegistration: {
    personalInformation: "Personal Information",
    name: "Name",
    socialName: "Social Name",
    socialNamePlaceholder: "Social name",
    namePlaceholder: "Full name",
    dateOfBirth: "Date of Birth",
    address: {
      title: "Address",
      state: "State",
      city: "City",
      neighborhood: "Neighborhood",
      zipCode: "ZIP Code",
      zipCodePlaceholder: "xxxxxxxx",
      street: "Street",
      number: "Number",
      numberPlaceholder: "Number",
      complement: "Complement",
      complementPlaceholder: "Apartment, block, house, etc.",
    },
    enrollmentDate: "Registration Date",
    documents: "Documents",
    registrationNumber: "Identity Document (CPF)",
    attachments: "Attachments",
    attachMoreFiles: "Attach more documents",
    selectFiles: "Select file",
    selectedFile: "Selected file:",
    fileCreatedAt: "File creation date:",
    fileDescription: "File description",
    cancelFileSend: "Cancel file upload",
    addFileButton: "Add file",
    toggleStudentStatusOn: "Activate student",
    toggleStudentStatusOff: "Deactivate student",
    details: "Details",
    schoolName: "Current School",
    schoolNamePlaceholder: "Enter student's current school",
    editButton: "Edit",
    saveButton: "Save",
    cancelButton: "Cancel",
    successMessage: "Student registered successfully!",
    updateSuccess: "Student updated successfully!",
    errorMessage: "Error registering student. Please try again.",
    confirmationMessage: "Are you sure you want to disable the student?",
    activationConfirmationMessage: "Are you sure you want to activate the student?",
    deactivationSuccess: "Student deactivated successfully",
    activationSuccess: "Student activated successfully",
    errors: {
      fullNameRequired: "Student full name is required",
      dateOfBirthRequired: "Student date of birth is required",
      registrationNumberRequired: "Student registration number is required",
      schoolYearRequired: "Student school year is required",
      genderRequired: "Student gender is required",
      enrollmentDateRequired: "Student enrollment date is required",
      addressCepRequired: "Student address ZIP code is required",
      addressNumberRequired: "Student address number is required",
      internalError: "Internal server error",
      studentNotFound: "Student not found",
      invalidData: "Invalid data",
      searchStudentError: "Error searching for student",
    },
  },
  studentEdition: {
    personalInformation: "Personal Information",
    name: "Name",
    namePlaceholder: "Full name",
    dateOfBirth: "Date of Birth",
    address: {
      zipCode: "ZIP Code",
      zipCodePlaceholder: "xxxxxxxx",
      street: "Street",
      number: "Number",
      numberPlaceholder: "Number",
      complement: "Complement",
      complementPlaceholder: "Apartment, block, house, etc.",
    },
    enrollmentDate: "Registration Date",
    documents: "Documents",
    registrationNumber: "Identity Document (CPF)",
    attachments: "Attachments",
    attachMoreFiles: "Attach more documents",
    selectFiles: "Select file",
    selectedFile: "Selected file:",
    fileCreatedAt: "File creation date:",
    fileDescription: "File description",
    cancelFileSend: "Cancel file upload",
    addFileButton: "Add file",
    details: "Details",
    schoolName: "Current School",
    schoolNamePlaceholder: "Enter student's current school",
    successMessage: "Student registered successfully!",
    errorMessage: "Error registering student. Please try again.",
  },
  students: {
    title: "Students",
    createNew: "Add Student",
    viewResponsible: "View Guardians",
    loadingStudents: "Loading students...",
    studentsError: "Error loading students",
    noStudents: "No students found",
    viewStudent: "View Details",
    birthday: ({ date }: Params<"date">) => `Birthday: ${date}`,
    registrationNumber: ({ registrationNumber }: Params<"registrationNumber">) => `CPF: ${registrationNumber}`,
    status: ({ status }: Params<"status">) => `Status: ${status}`,
    filter:{
      search: "Student name",
      title: "Name"
    }
  },
  studentsResponsibles: {
    title: "Responsibles",
    loadingResponsibles: "Loading Responsibles...",
    responsiblesError: "Error loading Responsibles",
    noResponsibles: "No Responsibles found",
    registerResponsible: "Register Responsible",
  },
  techDemo: {
    title: "Tech Demo",
    fetching: "Updating...",
    showAPIInfo: "Show API information",
    buttons: {
      openSuccessToast: "Open SUCCESS toast!",
      openErrorToast: "Open ERROR toast!",
      openInfoToast: "Open INFO toast!",
      openModal: "Open modal",
      openClassesModal: "Create Class Modal",
      testToast: "Test Toast",
      testCloseableToast: "Test Closeable Toast"
    },
    home: "Home",
    children: {
      mockAPI: {
        detail: ({ c2 }: Params<"c2">) => (
          `Received a URL parameter: ${c2}`
        ),
        apiError: ({ message }: Params<"message">) => (
          `API Error: ${message}`
        ),
      },
    }
  },
  textCard: {
    exploreHome: "Visit Home Page",
  },
  toast: {
    success: ({ message }: Params<"message">) => (`Success: ${message}`),
    error: ({ message }: Params<"message">) => (`Error: ${message}`),
    info: ({ message }: Params<"message">) => (`Info: ${message}`),
    warning: ({ message }: Params<"message">) => (`Warning: ${message}`),
  },
  userProfile: {
    logout: "Sign out",
    switchToEnglish: "Switch to English",
    switchToPortuguese: "Switch to Portuguese",
    goBack: "Go Back"
  },
  users: {
    title: "Manage Users",
    loadingUsers: "Loading users...",
    usersError: "Error loading users",
    registerNew: "Register New User",
    table: {
      id: "ID",
      name: "Name",
      email: "Email",
      status: "Status",
      role: "Role",
      actions: "Actions",
    },
    status: {
      active: "Active",
      inactive: "Inactive",
    },
    actions: {
      edit: "Edit",
      activate: "Activate",
      deactivate: "Deactivate",
    },
    footer: {
      showing: ({ count, total }: Params<"count" | "total">) => `Showing ${count} of ${total} ${total === "1" ? "user" : "users"}`,
      updatedAt: ({ when }: Params<"when">) => (
        `Updated at ${when}`
      )
    },
    inputs: {
      name: "Colaborator Name",
      namePlaceholder: "Full Name",
      email: "Email",
      emailPlaceholder: "full.name@wimbelemdon.com.br",
      register: "Register",
    },
    toasts: {
      enabled: "User activated successfully",
      disabled: "User deactivated successfully",
      toggleError: "Couldn't update user status. Please try again.",
    },
  },
  newActivityModal: {
    title: "New Activity",
    textFieldTitle: "Activity Name",
    textFieldPlaceholder: "Insert name",
    buttonText: "Register",
    successToast: ({ activityName }: Params<"activityName">) => (
      `Activity "${activityName}" registered!`
    ),
    editSuccessToast: ({ activityName }: Params<"activityName">) => `Activity "${activityName}" updated successfully!`,
  },
} as const;
