import type { Params } from "./type";

export const portugueseTextMap = {
  activityList: {
    title: "Lista de Atividades",
    createNew: "Criar Nova Atividade",
    newActivity: "Nova Atividade",
    activityName: "Nome da Atividade",
    loadingActivities: "Carregando atividades...",
    activitiesError: "Erro ao carregar atividades",
    activitiesEmpty: "Nenhuma atividade encontrada.",
    viewClasses: "Ver Turmas",
    filters: {
      name: {
        title: "Nome",
        placeholder: "Nome da Atividade",
      },
      area: {
        title: "Área",
        placeholder: "Selecione a Área",
        sports: "Esportes",
        gym: "Academia",
        water: "Aquáticos",
      },
      frequency: {
        title: "Frequência",
        placeholder: "Selecione a Frequência",
        daily: "Diária",
        weekly: "Semanal",
        monthly: "Mensal",
      },
    },
    card: {
      area: "Área:",
      frequency: "Frequência:",
      teacher: "Professor:",
    },
  },
  anamnesis: {
    title: "Formulário de Anamnese",
    createNew: "Criar novo formulário",
    previousForms: "Formulários Anteriores",
    skip: "Pular",
    save: "Salvar",
    selectOrCreate: "Selecione um formulário ou crie um novo.",
  },
  classes: {
    title: "Minhas Turmas",
    loadingClasses: "Carregando turmas...",
    classesError: "Erro ao carregar turmas",
    createClass: "Criar turma",
    weekDay: "Dia da semana",
    schedule: "Horário",
    level: "Nível",
    activity: "Atividade",
    card: {
      level: "Nível:",
      teacher: "Responsável:"
    },
  },
  classDetails: {
    loading: "Carregando turma...",
    errorLoading: "Não foi possível carregar os dados da turma.",
    classNotFound: "Turma não encontrada.",
    editClass: "Editar Turma",
    professor: "Responsável",
    level: "Nível",
    frequency: "Frequência",
    noStudents: "Nenhum aluno cadastrado nesta turma.",
  },
  dateInput: {
    selectDate: "Selecione a data",
  },
  errorBoundary: {
    title: "Ops",
    message: "Algo deu errado. Você pode recarregar a página ou voltar para a tela inicial.",
    goHome: "Ir para a página inicial",
    reload: "Recarregar",
  },
  filters: {
    loading: "Carregando filtros...",
    all: "Todos",
    formType: {
      title: "Tipo de Formulário",
      psychology: "Psicologia",
      social: "Assistência Social",
    },
    userStatus: {
      title: "Status do Usuário",
      active: "Ativo",
      inactive: "Inativo",
    },
    studentStatus: {
      title: "Status do Estudante",
      active: "Ativo",
      inactive: "Inativo",
    },
    frequencyStatus: {
      title: "Status de Frequência",
      present: "Presente",
      absent: "Ausente",
    },
    classState: {
      title: "Estado da Turma",
      active: "Ativa",
      inactive: "Inativa",
    },
    race: {
      title: "Raça",
      white: "Branca",
      black: "Preta",
      brown: "Parda",
      yellow: "Asiática",
      indigenous: "Indígena",
      notDeclared: "Não Declarado",
    },
    gender: {
      title: "Sexo",
      male: "Masculino",
      female: "Feminino",
      transMan: "Homem Trans",
      transWoman: "Mulher Trans",
      nonBinary: "Não Binário",
      other: "Outro",
    },
    socialPrograms: {
      title: "Programas Sociais",
      bolsaFamilia: "Bolsa Família",
      bpcLoas: "BPC/LOAS",
      tarifaSocialDeEnergia: "Tarifa Social de Energia",
      auxilioGas: "Auxílio Gás",
      programaEstadual: "Programa Estadual",
      programaMunicipalViaCras: "Programa Municipal via CRAS",
    },
    employmentStatus: {
      title: "Vínculo Empregatício",
      student: "Estudante",
      employed: "Empregado",
      unemployed: "Desempregado",
      intern: "Estagiário",
      apprentice: "Aprendiz",
      selfEmployed: "Autônomo",
      other: "Outro",
    },
    schoolYear: {
      title: "Ano Escolar",
      infantileEducation: "Educação Infantil",
      elementary1: "Fundamental 1",
      elementary2: "Fundamental 2",
      elementary3: "Fundamental 3",
      elementary4: "Fundamental 4",
      elementary5: "Fundamental 5",
      elementary6: "Fundamental 6",
      elementary7: "Fundamental 7",
      elementary8: "Fundamental 8",
      elementary9: "Fundamental 9",
      highSchool1: "Ensino Médio 1",
      highSchool2: "Ensino Médio 2",
      highSchool3: "Ensino Médio 3",
      eja: "EJA",
    },
    educationLevel: {
      title: "Nível de Escolaridade",
      none: "Nenhum",
      literate: "Alfabetizado",
      incompleteElementary: "Fundamental Incompleto",
      completeElementary: "Fundamental Completo",
      incompleteHighSchool: "Ensino Médio Incompleto",
      completeHighSchool: "Ensino Médio Completo",
      incompleteHigher: "Superior Incompleto",
      completeHigher: "Superior Completo",
      posGraduation: "Pós-Graduação",
    },
    noteTypes: {
      title: "Tipo de Nota",
      medical: "Atestado Médico",
      none: "Sem Justificativa",
      empty: "(vazio)",
    },
    weekDays: {
      title: "Dia da Semana",
      monday: "Segunda-feira",
      tuesday: "Terça-feira",
      wednesday: "Quarta-feira",
      thursday: "Quinta-feira",
      friday: "Sexta-feira",
      saturday: "Sábado",
      sunday: "Domingo",
    },
    role: {
      title: "Papel",
      admin: "Administrador",
      manager: "Gerente",
      teacher: "Professor",
      psychologist: "Psicólogo",
      psychology_intern: "Estagiário de Psicologia",
      social_worker: "Assistente Social",
      social_work_intern: "Estagiário de Assistência Social"
    },
    identityTypes: {
      title: "Tipo de Documento",
      rg: "RG",
      cpf: "CPF",
      birthCertificate: "Certidão de Nascimento",
      driverLicense: "CNH",
      passport: "Passaporte",
      voterRegistration: "Título de Eleitor",
      ctps: "CTPS",
      other: "Outro",
    },
    documentTypes: {
      title: "Tipo de Documento",
      residenceProof: "Comprovante de Residência",
      incomeProof: "Comprovante de Renda",
      other: "Outro",
    },
    levels: {
      title: "Nível",
      beginner: "Iniciante",
      intermediate: "Intermediário",
      advanced: "Avançado",
    },
    civilStates: {
      title: "Estado Civil",
      single: "Solteiro(a)",
      married: "Casado(a)",
      divorced: "Divorciado(a)",
      widowed: "Viúvo(a)",
      stableUnion: "União Estável",
    },
  },
  frequency: {
    title: "Realizar Chamada",
    loadingActivities: "Carregando atividades...",
    activitiesError: "Erro ao carregar atividades",
  },
  frequencyCall: {
    title: ({ activity, classTitle }: Params<"activity" | "classTitle">) => (
      `Chamada - ${activity} - ${classTitle}`
    ),
    loadingStudents: "Carregando estudantes...",
    studentsError: "Erro ao carregar estudantes",
    errorNoStudents: "Erro ao salvar a chamada, estudantes não encontrados",
    errorNoDate: "Erro ao salvar chamada, por favor insira uma data",
    successSave: "Chamada registrada com sucesso",
  },
  frequencyCard: {
    absentDetails: "Adicionar Observação",
    frequency: ({ percent }: Params<"percent">) => (
      `Frequência: ${percent}%`
    ),
    active: "Ativo",
    inactive: "Inativo",
  },
  frequencyClasses: {
    title: ({ activity }: Params<"activity">) => `Realizar Chamada - ${activity}`,
    loadingClasses: "Carregando turmas...",
    classesError: "Erro ao carregar turmas",
    noClasses: "Nenhuma turma encontrada para esta atividade.",
    goBack: "Voltar para Atividades",
  },
  frequencyGeneralCall: {
    title: "Chamada Geral",
    save: "Salvar",
    loadingStudents: "Carregando estudantes...",
    studentsError: "Erro ao carregar estudantes",
    errorNoStudents: "Erro ao salvar a chamada, estudantes não encontrados",
    errorNoDate: "Erro ao salvar chamada, por favor insira uma data",
    successSave: "Frequência salva com sucesso",
    errorInvalidDate: "Formato de data inválido",
    errorServer: "Erro inesperado no servidor",
  },
  genericActions: {
    cancel: "Cancelar",
    create: "Criar",
    delete: "Excluir",
    edit: "Editar",
    loading: "Carregando...",
    save: "Salvar",
    saveEdit: "Salvar Alterações",
    viewDetails: "Ver Detalhes",
    toggleStatusOn: "Ativar",
    toggleStatusOff: "Desativar",
  },
  header: {
    goToHome: "Ir para a página inicial",
    logoAlt: "Logotipo do WimBelemDon",
  },
  home: {
    welcomeBack: "Bem vindo(a) de volta",
    cards: {
      takeAttendance: "Realizar Chamada",
      manageStudents: "Gerenciar Alunos",
      manageActivities: "Gerenciar Atividades",
      manageClasses: "Gerenciar Turmas",
      manageUsers: "Gerenciar Usuários"
    },
  },
  login: {
    title: "Login",
    loginWithGoogle: "Entrar com Google",
    loggingIn: "Entrando...",
    logoAlt: "Logo",
    errors: {
      invalidToken: "Token de login inválido. Tente novamente.",
      notRegistered: "Sua conta não está registrada no sistema.",
      inactive: "Sua conta não está ativa. Entre em contato com um administrador.",
      popupClosed: "O login foi cancelado antes de finalizar.",
      popupBlocked: "O pop-up de login foi bloqueado pelo navegador.",
      popupCancelled: "Outra tentativa de login já estava em andamento.",
      network: "Erro de rede durante o login. Verifique sua conexão e tente novamente.",
      generic: "Não foi possível fazer login. Tente novamente.",
    }
  },
  newResponsibleModal: {
    title: "Cadastrar Responsável",
    editTitle: "Editar Responsável",
    updateButton: "Atualizar Responsável",
    updateSuccessMessage: "Responsável atualizado com sucesso!",
    updateErrorMessage: "Erro ao atualizar responsável. Por favor, tente novamente.",
    createErrorMessage: "Erro ao criar responsável. Por favor, tente novamente.",
    waitAddressLoading: "Por favor, aguarde o carregamento do endereço completo",
    errorLoadingResponsible: "Erro ao carregar dados do responsável",
    studentIdRequired: "ID do estudante é obrigatório",
    buttonText: "Adicionar Responsável",
    personalInformation: "Informações Pessoais",
    employmentInformation: "Situação Empregatícia",
    addressInformation: "Endereço",
    inputs: {
      name: "Nome Completo",
      namePlaceholder: "Digite o nome completo do responsável",
      socialName: "Nome Social",
      socialNamePlaceholder: "Digite o nome social do responsável",
      cpf: "CPF",
      cpfPlaceholder: "Digite o CPF do responsável",
      registrationNumber: "CPF",
      registrationNumberPlaceholder: "Digite o CPF do responsável",
      birthDate: "Data de Nascimento",
      birthDatePlaceholder: "Digite a data de nascimento do responsável",
      civilState: "Estado Civil",
      civilStatePlaceholder: "Selecione o estado civil do responsável",
      nis: "NIS",
      nisPlaceholder: "Digite o NIS do responsável",
      phone: "Telefone",
      phonePlaceholder: "Digite o telefone do responsável",
      email: "Email",
      emailPlaceholder: "Digite o email do responsável",
      relationship: "Parentesco",
      relationshipPlaceholder: "Digite o parentesco com o educando",
      race: "Raça",
      racePlaceholder: "Selecione a raça",
      gender: "Gênero",
      genderPlaceholder: "Selecione o gênero",
      educationLevel: "Nível de Escolaridade",
      educationLevelPlaceholder: "Selecione o nível de escolaridade",
      socialPrograms: "Programas Sociais",
      socialProgramsPlaceholder: "Selecione os programas sociais",
      employmentStatus: "Situação de Emprego",
      employmentStatusPlaceholder: "Selecione a situação de emprego",
      street: "Rua",
      streetPlaceholder: "Digite o endereço da rua",
      neighborhood: "Bairro",
      neighborhoodPlaceholder: "Digite o bairro",
      city: "Cidade",
      cityPlaceholder: "Digite a cidade",
      state: "Estado",
      statePlaceholder: "Digite o estado",
      cep: "CEP",
      cepPlaceholder: "Digite o CEP",
      number: "Número",
      numberPlaceholder: "Digite o número",
      complement: "Complemento",
      complementPlaceholder: "Apartamento, bloco, casa, etc.",
      address: "Endereço",
      addressPlaceholder: "Digite o endereço do responsável",
    },
    requiredFields: {
      fullName: "Nome completo é obrigatório.",
      registrationNumber: "CPF é obrigatório.",
      birthDate: "Data de nascimento é obrigatória.",
      phone: "Telefone é obrigatório.",
      relationship: "Parentesco é obrigatório.",
      cep: "CEP é obrigatório.",
      number: "Número é obrigatório.",
    },
    successMessage: "Responsável adicionado com sucesso!",
    pleaseFillAllFields: "Por favor, preencha todos os campos obrigatórios.",
  },
  notFound: {
    title: "Página não encontrada",
    message: "A página que você tentou acessar não existe.",
    goHome: "Ir para a página inicial",
    reload: "Recarregar",
  },
  classesModal: {
    recurring: "Atividade Recorrente",
    inputs: {
      className: "Nome da Turma",
      classLevel: "Nível da Turma",
      startDate: "Data de InÍcio",
      endDate: "Data de Encerramento",
      startTime: "Horário de Início",
      endTime: "Horário de Término",
      level: "Nível",
      searchTeacher: "Pesquisar Professor",
      assignTeacher: "Atribuir Professor",
      searchStudent: "Pesquisar Educando",
      addStudent: "Adicionar Educando",
    },
    buttons: {
      next: "Próximo",
      back: "Voltar",
      create: "Cadastrar",
    },
    steps: {
      data: "Dados",
      teacher: "Professor",
      student: "Educando",
    },
    createSuccessMessage: "Turma criada com sucesso!",
    createErrorFillAllFields: "Por favor, preencha todos os campos.",
    createErrorGeneric: "Erro ao criar turma. Por favor, tente novamente.",
  },
  personCard: {
    userImageAlt: "Imagem do usuário",
    name: "Nome:",
    registrationNumber: "CPF:",
    nis: "NIS:",
    phoneNumber: "Telefone:",
    email: "Email:",
    address: "Endereço:",
    fullName: "Nome completo:",
    socialName: "Nome social:",
    dateOfBirth: "Data de nascimento:",
    relationship: "Parentesco:",
    race: "Raça:",
    gender: "Gênero:",
    educationLevel: "Escolaridade:",
    socialPrograms: "Programa social:",
    employmentStatus: "Situação de emprego:",
  },
  sidebar: {
    openSidebar: "Abrir menu lateral",
    listIcon: ({ to }: Params<"to">) => (
      `Navegar para a página ${to}`
    ),
    home: "Página Inicial",
    frequency: "Frequência",
    students: "Educandos",
    activities: "Atividades",
    classes: "Turmas",
    users: "Usuários",
    techDemo: "Tech Demo",
  },
  studentRegistration: {
    personalInformation: "Informações Pessoais",
    name: "Nome",
    socialName: "Nome social",
    namePlaceholder: "Nome completo",
    socialNamePlaceholder: "Nome social",
    dateOfBirth: "Data de Nascimento",
    address: {
      title: "Endereço",
      state: "Estado",
      city: "Cidade",
      neighborhood: "Bairro",
      zipCode: "CEP",
      zipCodePlaceholder: "xxxxxxxx",
      street: "Logradouro",
      number: "Número",
      numberPlaceholder: "Número",
      complement: "Complemento",
      complementPlaceholder: "Apartamento, bloco, casa, etc.",
    },
    enrollmentDate: "Data de Cadastro",
    documents: "Documentos",
    registrationNumber: "Documento de Identidade (CPF)",
    attachments: "Anexos",
    attachMoreFiles: "Anexar mais documentos",
    viewFiles: "Ver arquivos anexados",
    documentAdded: "Documento adicionado com sucesso!",
    selectFiles: "Selecionar arquivo",
    selectedFile: "Arquivo selecionado:",
    fileCreatedAt: "Data de criação do arquivo:",
    fileDescription: "Descrição do arquivo",
    cancelFileSend: "Cancelar envio do arquivo",
    addFileButton: "Adicionar arquivo",
    details: "Detalhes",
    schoolName: "Escola Atual",
    schoolNamePlaceholder: "Digite a escola atual do Educando",
    editButton: "Editar",
    saveButton: "Salvar",
    cancelButton: "Cancelar",
    successMessage: "Estudante cadastrado com sucesso!",
    updateSuccess: "Estudante atualizado com sucesso!",
    errorMessage: "Erro ao cadastrar estudante. Por favor, tente novamente.",
    confirmationMessage: "Tem certeza que deseja desativar este educando?",
    activationConfirmationMessage: "Tem certeza que deseja ativar este educando?",
    deactivationSuccess: "Estudante desativado com sucesso",
    activationSuccess: "Estudante ativado com sucesso",
    errors: {
      fullNameRequired: "O nome completo do estudante é obrigatório",
      dateOfBirthRequired: "A data de nascimento do estudante é obrigatória",
      registrationNumberRequired: "O número de documento do estudante é obrigatório",
      schoolYearRequired: "O nível de escolaridade do estudante é obrigatório",
      genderRequired: "O gênero do estudante é obrigatório",
      enrollmentDateRequired: "A data de cadastro do estudante é obrigatória",
      addressCepRequired: "O CEP do endereço do estudante é obrigatório",
      addressNumberRequired: "O número do endereço do estudante é obrigatório",
      internalError: "Erro interno no servidor",
      studentNotFound: "Aluno não encontrado",
      invalidData: "Dados inválidos",
      searchStudentError: "Erro ao buscar o aluno",
    },
  },
  studentEdition: {
    personalInformation: "Informações Pessoais",
    name: "Nome",
    namePlaceholder: "Nome completo",
    dateOfBirth: "Data de Nascimento",
    address: {
      zipCode: "CEP",
      zipCodePlaceholder: "xxxxxxxx",
      street: "Logradouro",
      number: "Número",
      numberPlaceholder: "Número",
      complement: "Complemento",
      complementPlaceholder: "Apartamento, bloco, casa, etc.",
    },
    enrollmentDate: "Data de Cadastro",
    documents: "Documentos",
    registrationNumber: "Documento de Identidade (CPF)",
    attachments: "Anexos",
    attachMoreFiles: "Anexar mais documentos",
    selectFiles: "Selecionar arquivo",
    selectedFile: "Arquivo selecionado:",
    fileCreatedAt: "Data de criação do arquivo:",
    fileDescription: "Descrição do arquivo",
    cancelFileSend: "Cancelar envio do arquivo",
    addFileButton: "Adicionar arquivo",
    toggleStudentStatusOn: "Ativar estudante",
    toggleStudentStatusOff: "Desativar estudante",
    details: "Detalhes",
    schoolName: "Escola Atual",
    schoolNamePlaceholder: "Digite a escola atual do Educando",
    successMessage: "Estudante cadastrado com sucesso!",
    errorMessage: "Erro ao cadastrar estudante. Por favor, tente novamente.",
  },
  students: {
    title: "Educandos",
    createNew: "Adicionar Educando",
    viewResponsible: "Ver Responsáveis",
    loadingStudents: "Carregando educandos...",
    studentsError: "Erro ao carregar educandos",
    noStudents: "Nenhum educando encontrado",
    viewStudent: "Ver Detalhes",
    birthday: ({ date }: Params<"date">) => `Aniversário: ${date}`,
    registrationNumber: ({ registrationNumber }: Params<"registrationNumber">) => `CPF: ${registrationNumber}`,
    status: ({ status }: Params<"status">) => `Status: ${status}`,
    filter:{
      search: "Nome do educando",
      title: "Nome"
    },
  },
  studentsResponsibles: {
    title: "Responsáveis",
    loadingResponsibles: "Carregando responsáveis...",
    responsiblesError: "Erro ao carregar responsáveis",
    noResponsibles: "Nenhum responsável encontrado",
    registerResponsible: "Cadastrar Responsável",
  },
  techDemo: {
    title: "Tech Demo",
    fetching: "Atualizando...",
    showAPIInfo: "Mostrar informações da API",
    buttons: {
      openSuccessToast: "Abrir toast de SUCESSO!",
      openErrorToast: "Abrir toast de ERRO!",
      openInfoToast: "Abrir toast de INFO!",
      openModal: "Abrir Modal",
      openClassesModal: "Abrir Modal de Turma",
      testToast: "Teste de Toast",
      testCloseableToast: "Teste de Toast fechável",
    },
    home: "Home",
    children: {
      mockAPI: {
        detail: ({ c2 }: Params<"c2">) => (
          `Recebi um parâmetro na URL: ${c2}`
        ),
        apiError: ({ message }: Params<"message">) => (
          `Erro na API: ${message}`
        ),
      },
    }
  },
  textCard: {
    exploreHome: "Visitar Página Inicial",
  },
  toast: {
    success: ({ message }: Params<"message">) => (`Sucesso: ${message}`),
    error: ({ message }: Params<"message">) => (`Erro: ${message}`),
    info: ({ message }: Params<"message">) => (`Info: ${message}`),
    warning: ({ message }: Params<"message">) => (`Aviso: ${message}`),
  },
  userProfile: {
    logout: "Sair",
    switchToEnglish: "Mudar para Inglês",
    switchToPortuguese: "Mudar para Português",
    goBack: "Voltar"
  },
  users: {
    title: "Gerenciar Usuários",
    loadingUsers: "Carregando usuários...",
    usersError: "Erro ao carregar usuários",
    registerNew: "Registrar Novo Usuário",
    table: {
      id: "ID",
      name: "Nome",
      email: "Email",
      status: "Status",
      role: "Papel",
      actions: "Ações",
    },
    status: {
      active: "Ativo",
      inactive: "Inativo",
    },
    actions: {
      edit: "Editar",
      activate: "Ativar",
      deactivate: "Desativar",
    },
    footer: {
      showing: ({ count, total }: Params<"count" | "total">) => `Mostrando ${count} de ${total} ${total === "1" ? "usuário" : "usuários"}`,
      updatedAt: ({ when }: Params<"when">) => `Atualizado em ${when}`
    },
    inputs: {
      name: "Nome do Colaborador",
      namePlaceholder: "Nome Completo",
      email: "Email",
      emailPlaceholder: "nome.completo@wimbelemdon.com.br",
      register: "Cadastrar",
    },
    toasts: {
      enabled: "Usuário ativado com sucesso",
      disabled: "Usuário desativado com sucesso",
      toggleError: "Não foi possível atualizar o status do usuário. Tente novamente.",
    },
  },
  newActivityModal: {
    title: "Nova Atividade",
    textFieldTitle: "Nome da Atividade",
    textFieldPlaceholder: "Insira o nome",
    buttonText: "Cadastrar",
    successToast: ({ activityName }: Params<"activityName">) => (
      `Atividade "${activityName}" cadastrada!`
    ),
    editSuccessToast: ({ activityName }: Params<"activityName">) => `Atividade "${activityName}" atualizada com sucesso!`,
  },
} as const;
