name: Cypress Tests

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  cypress-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: http://localhost:4173/frontend
          CYPRESS_USE_MOCK_API_DATA: true
        with:
          start: npm run preview
          wait-on: 'http://localhost:4173'
          wait-on-timeout: 60
          command: npm run test
